export enum ActionStatus {
    //For every actions
    REQ_SELECT_CURRENCY = "REQ_SELECT_CURRENCY",
    REQ_INPUT_AMOUNT = "REQ_INPUT_AMOUNT",

    //For swap & add liquidity actions
    INSUFFICIENT_INPUT_CURRENCY_AMOUNT = "INSUFFICIENT_INPUT_CURRENCY_AMOUNT",
    INSUFFICIENT_OUTPUT_CURRENCY_AMOUNT = "INSUFFICIENT_OUTPUT_CURRENCY_AMOUNT",
    REQ_WRAP_INPUT_CURRENCY = "REQ_WRAP_INPUT_CURRENCY",
    REQ_WRAP_OUTPUT_CURRENCY = "REQ_WRAP_OUTPUT_CURRENCY",
    REQ_APPROVE_INPUT_CURRENCY = "REQ_APPROVE_INPUT_CURRENCY",
    REQ_APPROVE_OUTPUT_CURRENCY = "REQ_APPROVE_OUTPUT_CURRENCY",

    //For remove liquidity action
    REQ_APPROVE_LIQUIDITY = "REQ_APPROVE_LIQUIDITY",
    INSUFFICIENT_LIQUIDITY_AMOUNT = "INSUFFICIENT_LIQUIDITY_AMOUNT",
    
    //For import pool action
    REQ_ADD_LIQUIDITY = "REQ_ADD_LIQUIDITY",

    //Others
    REQ_EXECUTE_ACTION = "REQ_EXECUTE_ACTION",
    PENDING = "PENDING",
    LOADING = "LOADING",
}